#!/bin/bash
# ============================================================
# Step 3 — Deploy the 4 capability apps to Code Engine (one per capability, all
# from the same image). Serves MCP over HTTP at /mcp/<domain>.
#
# DATA_SOURCE=mount (default): mounts the COS pds at the paths the servers expect.
# DATA_SOURCE=sync           : app downloads data from COS to ephemeral disk on start.
#
# Writes deploy/ce/.ce_urls.env — `source` it before benchmarking against CE.
# Idempotent: re-running updates the apps in place.
# ============================================================
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}/config.sh"
admin_guard "${1:-}"
require_login
ce_target

# A per-deploy revision stamp. The image tag is ':latest', and CE only re-pulls a
# tag when it creates a NEW revision — so we change this env every deploy to force
# a fresh revision (and thus pick up a rebuilt image).
DEPLOY_REV="$(date +%s)"

# Build the common flags for one app.  $1=app name  $2=capability id
deploy_app() {
  local name="$1" cap="$2"
  local cpu="$CPU" mem="$MEMORY" eph="$EPHEMERAL"
  if [[ "$cap" == "4" ]]; then cpu="$CAP4_CPU"; mem="$CAP4_MEMORY"; eph="$CAP4_EPHEMERAL"; fi

  local args=(
    --image "$IMAGE_REF"
    --registry-secret "$REGISTRY_SECRET_NAME"
    --port "$BRIDGE_PORT"
    --min-scale "$MIN_SCALE" --max-scale "$MAX_SCALE"
    --cpu "$cpu" --memory "$mem" --ephemeral-storage "$eph"
    --env "SERVE_MODE=http"
    --env "CAPABILITY_ID=$cap"
    --env "BRIDGE_PORT=$BRIDGE_PORT"
    --env "DATA_SOURCE=$DATA_SOURCE"
    --env "DEPLOY_REV=$DEPLOY_REV"
    --request-timeout 600
  )

  if [[ "$DATA_SOURCE" == "mount" ]]; then
    # Mount the COS bucket subpaths at the exact paths the servers already use.
    args+=( --mount-data-store "/app/db=${PDS_NAME}:databases" )
    args+=( --mount-data-store "/app/environment/configs=${PDS_NAME}:configs" )
    if [[ "$cap" == "4" ]]; then
      args+=( --mount-data-store "/app/retrievers/chroma_data=${PDS_NAME}:indexed_documents" )
      args+=( --mount-data-store "/app/retrievers/queries=${PDS_NAME}:queries" )
    fi
  else
    # sync mode: give the container the creds + coordinates to pull from COS.
    args+=( --env "COS_ENDPOINT=$COS_ENDPOINT" )
    args+=( --env "COS_BUCKET=$COS_BUCKET" )
    args+=( --env "COS_ACCESS_KEY_ID=$COS_HMAC_ACCESS_KEY_ID" )
    args+=( --env "COS_SECRET_ACCESS_KEY=$COS_HMAC_SECRET_ACCESS_KEY" )
  fi

  # Delete + recreate for a clean redeploy. `ce app update` can't re-apply an
  # existing --mount-data-store ("duplicate") and has no --unmount, so recreating
  # is the reliable way to refresh mounts/env and re-pull :latest. The app name
  # (hence the URL) is stable across delete/recreate.
  if ibmcloud ce app get -n "$name" >/dev/null 2>&1; then
    echo "Deleting existing app '$name' for a clean redeploy ..."
    ibmcloud ce app delete --name "$name" --force --wait --ignore-not-found
  fi
  echo "Creating app '$name' (capability $cap, data=$DATA_SOURCE) ..."
  ibmcloud ce app create --name "$name" "${args[@]}"
}

deploy_app "$APP_CAP1" 1
deploy_app "$APP_CAP2" 2
deploy_app "$APP_CAP3" 3
deploy_app "$APP_CAP4" 4

# Capture the public URLs into .ce_urls.env for the benchmark client + explorer.
echo "# Generated by deploy/ce/3_deploy_apps.sh — source before benchmarking CE." > "$URLS_ENV_FILE"
i=1
for name in "$APP_CAP1" "$APP_CAP2" "$APP_CAP3" "$APP_CAP4"; do
  url=$(ibmcloud ce app get --name "$name" --output url)
  echo "export VAKRA_CAP${i}_URL=\"$url\"" >> "$URLS_ENV_FILE"
  i=$((i+1))
done

echo ""
echo "==================================================="
echo " VAKRA capability apps are live. URLs written to:"
echo "   $URLS_ENV_FILE"
cat "$URLS_ENV_FILE"
echo "==================================================="
echo ""
echo "Test it:"
echo "   source $URLS_ENV_FILE"
echo "   python deploy/ce/5_test_ce.py"
echo "   python benchmark_runner.py --capability_id 2 --domain address \\"
echo "       --mcp-config benchmark/mcp_connection_config.ce.yaml"
echo ""
echo "Optional hosted explorer:  VAKRA_CE_ADMIN=1 ./4_deploy_explorer.sh"
